backend/backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^radio/', include('radio.urls')),
    url(r'^admin/', admin.site.urls),
]

backend/emissions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: animateurs/
    url(r'^$', views.animateurs_liste, name="animateurs_liste"),
    # ex: animateurs/4/
    url(r'(?P<animateur_id>[0-9]+)/$', views.animateur_details, name="animateur_details"),
    #
    url(r'^$', views.index, name='index'),
]

backend/radio/urls.py
from django.conf.urls import url

from . import views

app_name = 'radio'
urlpatterns = [
    url(r'^$', views.directView, name='index'),
    url(r'^direct/$', views.directView, name='direct'),
    url(r'^animateurs/$', views.AnimateursListeView.as_view(), name='animateurs_liste'),
    url(r'^animateurs/(?P<pk>[0-9]+)/$', views.AnimateurDetailsView.as_view(), name='animateur_details'),
    url(r'^animateurs/(?P<pk>[0-9]+)/emissions/$', views.AnimateurEmissionsView.as_view(), name='animateur-emissions'),

    url(r'^emissions/$', views.EmissionsListeView.as_view(), name='emissions_liste'),
    url(r'^emissions/(?P<pk>[0-9]+)/$', views.EmissionDetailsView.as_view(), name='emission_details'),
    url(r'^emissions/(?P<pk>[0-9]+)/animateurs/$', views.EmissionAnimateursView.as_view(), name='emission-animateurs'),
    url(r'^emissions/(?P<emission_id>[0-9]+)/(?P<enregistrement_id>[0-9]+)/$', views.EnregistrementDetailView.as_view(), name='emission_details'),

    url(r'^faq/$', views.faqView, name='faq'),
    url(r'^programme/$', views.ProgrammeView, name='programme'),
    url(r'^enregistrements/$', views.EnregistrementListeView.as_view(), name='enregistrements_liste'),
    url(r'^enregistrements/(?P<pk>[0-9]+)/$', views.EnregistrementDetailView.as_view(), name='enregistrement_details'),

    url(r'^albums/$', views.AlbumListeView.as_view(), name='albums_liste'),
]

backend/emissions/models.py
from django.db import models

# Create your models here.
class Animateur(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    surnom = models.CharField(max_length=50)
    role = models.CharField(max_length=100)

    def __str__(self):
        if len(self.surnom) > 0:
            return self.prenom + ' "' + self.surnom + '" ' + self.nom
        else:
            return self.prenom + ' ' + self.nom

class Emission(models.Model):
    nom = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200)
    date_derniere_diffusion = models.DateTimeField("Date de la derniere emission")
    contributeurs = models.ManyToManyField(Animateur)
    def __str__(self):
        return self.nom

class Enregistrement(models.Model):
    emission = models.ForeignKey(Emission)
    titre = models.CharField(max_length=200)
    date_diffusion = models.DateTimeField()
    def __str__(self):
        return self.emission.nom + " du " + self.date_diffusion.strftime('%d/%m')

backend/radio/models.py
from django.db import models

# Create your models here.
class Animateur(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    surnom = models.CharField(max_length=50)
    role = models.CharField(max_length=100)
    presentation = models.TextField(default="")
    allow_contact = models.BooleanField(default=False)
    email = models.EmailField(null=True)

    def __str__(self):
        if len(self.surnom) > 0:
            return self.prenom + ' "' + self.surnom + '" ' + self.nom
        else:
            return self.prenom + ' ' + self.nom

class Emission(models.Model):
    nom = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200)
    date_derniere_diffusion = models.DateTimeField("Date de la derniere emission")
    contributeurs = models.ManyToManyField(Animateur)
    description = models.TextField()
    dernier_episode = models.ForeignKey('Enregistrement', null=True, related_name='+')

    def __str__(self):
        return self.nom

class Album(models.Model):
    nom = models.CharField(max_length=200)
    album_art = models.CharField(max_length=200, blank=True, default='')
    artiste = models.CharField(max_length=200)
    annee = models.CharField(max_length=4)
    date_creation = models.DateTimeField("Date d'ajout", auto_now_add=True)
    description = models.TextField()
    lien_phoenix = models.CharField(default = '', max_length=300, blank=True)
    lien_deezer = models.CharField(default = '', max_length=300, blank=True)
    lien_spotify = models.CharField(default = '', max_length=300, blank=True)
    lien_youtube = models.CharField(default = '', max_length=300, blank=True)
    def __str__(self):
        return self.nom + " [" + self.artiste + "](" + self.annee + ")"



class Enregistrement(models.Model):
    emission = models.ForeignKey(Emission)
    edition_id = models.SmallIntegerField()
    titre = models.CharField(max_length=200)
    emission_url = models.CharField(max_length=200, default='demo.wav')
    date_diffusion = models.DateTimeField()
    description = models.TextField()
    def __str__(self):
        return self.emission.nom + " du " + self.date_diffusion.strftime('%d/%m')

class Programme(models.Model):
    titre = models.CharField(max_length=200, blank=True, default="")
    description = models.TextField()
    heure_debut = models.DateTimeField()
    heure_fin = models.DateTimeField()
    playlist_id = models.CharField(max_length=200, blank=True, default="")
    TOUS = '00TS'
    LUNDI = '01LU'
    MARDI = '02MA'
    MERCREDI = '03ME'
    JEUDI = '04JE'
    VENDREDI = '05VE'
    SAMEDI = '06SA'
    DIMANCHE = '07DI'
    jours_de_la_semaine = (
        (TOUS, 'Tous les jours'),
        (LUNDI, 'Lundi'),
        (MARDI, 'Mardi'),
        (MERCREDI, 'Mercredi'),
        (JEUDI, 'Jeudi'),
        (VENDREDI, 'Vendredi'),
        (SAMEDI, 'Samedi'),
        (DIMANCHE, 'Dimanche'),
        (None, 'Choisis un jour'),
    )
    jour = models.CharField(max_length=4, choices=jours_de_la_semaine, default=TOUS)

    def __str__(self):
        return self.titre

backend/emissions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Animateur
# Create your views here.
def index(request):
    return HttpResponse("Index des émissions")

def animateurs_liste(request):
    result = "Liste des animateurs : \n--\n"
    for anim in Animateur.objects.all():
        result += str(anim) + "\n"
    return HttpResponse(result)

def animateur_details(request, animateur_id):
    try:
        a = Animateur.objects.get(pk=animateur_id)
        result = "Nom : {}\nPrénom : {}\nRôle : {}"
        return HttpResponse(result.format(a.nom, a.prenom, a.role))
    except DoesNotExist:
        return HttpResponse("Animateur inconnu")

backend/radio/views.py
from django.shortcuts import render, get_object_or_404
from django.core import serializers
from django.views import generic
from django.http import HttpResponse

from .models import Animateur, Emission, Enregistrement, Programme, Album
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'radio/index.html'

def directView(request):
    return render(request, 'index.html', {})

class AnimateursListeView(generic.ListView):
    model = Animateur
    template_name = 'radio/animateurs.html'
    context_object_name = 'animateurs'

class AnimateurDetailsView(generic.DetailView):
    model = Animateur
    template_name = 'radio/animateur-details.html'
    def get_context_data(self, **kwargs):
        context = super(AnimateurDetailsView, self).get_context_data(**kwargs)
        context['ses_derniers_enregistrements'] = Enregistrement.objects.filter(emission__contributeurs__id=context['animateur'].id)

        return context

class AnimateurEmissionsView(generic.ListView):
    model = Emission
    template_name = 'radio/animateur-emissions.html'

class EmissionsListeView(generic.ListView):
    model = Emission
    template_name = 'radio/emissions.html'
    context_object_name = 'emissions'
    #
    # def get_context_data(self, **kwargs):
    #     context = super(EmissionsListeView, self).get_context_data(**kwargs)
    #     for emission in context['emissions']:
    #         emission.derniers_enregistrements = Enregistrement.objects.filter(emission_id = emission.id).order_by('-date_diffusion')

class EmissionDetailsView(generic.DetailView):
    model = Emission
    template_name = 'radio/emission-details.html'

    def get_context_data(self, **kwargs):
        context = super(EmissionDetailsView, self).get_context_data(**kwargs)
        context['derniers_enregistrements'] = Enregistrement.objects.filter(emission_id = context['emission'].id).order_by('-date_diffusion')
        return context

class EmissionAnimateursView(generic.ListView):
    model = Animateur
    template_name = 'radio/emission-animateurs.html'

class EnregistrementListeView(generic.ListView):
    model = Enregistrement
    template_name = 'radio/enregistrements.html'
    context_object_name = 'enregistrements'
    def get_queryset(self):
        return Enregistrement.objects.order_by('-date_diffusion')

class AlbumListeView(generic.ListView):
    model = Album
    template_name= 'radio/albums.html'
    context_object_name = 'albums'

def ProgrammeView(request):
    template_name = 'radio/programmes.html'
    tous = Programme.objects.filter(jour=Programme.TOUS).order_by('heure_debut')
    lundi = Programme.objects.filter(jour=Programme.LUNDI).order_by('heure_debut')
    mardi = Programme.objects.filter(jour=Programme.MARDI).order_by('heure_debut')
    mercredi = Programme.objects.filter(jour=Programme.MERCREDI).order_by('heure_debut')
    jeudi = Programme.objects.filter(jour=Programme.JEUDI).order_by('heure_debut')
    vendredi = Programme.objects.filter(jour=Programme.VENDREDI).order_by('heure_debut')
    samedi = Programme.objects.filter(jour=Programme.SAMEDI).order_by('heure_debut')
    dimanche = Programme.objects.filter(jour=Programme.DIMANCHE).order_by('heure_debut')
    data = [
        {'jour': 'tous les jours', 'programmes': tous},
        {'jour': 'lundi', 'programmes': lundi},
        {'jour': 'mardi', 'programmes': mardi},
        {'jour': 'mercredi', 'programmes': mercredi},
        {'jour': 'jeudi', 'programmes': jeudi},
        {'jour': 'vendredi', 'programmes': vendredi},
        {'jour': 'samedi', 'programmes': samedi},
        {'jour': 'dimanche', 'programmes': dimanche}
    ]
    # grille = {}
    # s = ""
    # for programme in Programme.objects.all():
    #     jour = programme.jour
    #     s += "  >jour:" + jour
    #     s += ">titre:" + programme.titre
    #     if jour in grille:
    #         grille[jour][programme.id] = programme
    #     else:
    #         grille[jour] = {programme.id: programme}


    return render(request, template_name,{'data': data})

class EnregistrementDetailView(generic.DetailView):
    model = Enregistrement
    template_name = 'radio/enregistrement-details.html'

def faqView(request):
    template_name = 'radio/participer.html'
    contact = get_object_or_404(Animateur, role="Prez")
    return render(request, template_name, {"contact": contact})

def enregistrement_details(request, emission_id, edition_id):
    #enreg = Enregistrement.objects.filter(emission_id=emission_id, edition_id=edition_id)
    enregistrement = get_object_or_404(Enregistrement, emission_id=emission_id, edition_id=edition_id)
    return render(request, 'radio/enregistrement-details.html', {'enregistrement' : enregistrement})

def animateurs_liste(request):
    animateurs = Animateur.objects.all()
    templateURL = 'radio/animateurs.html'
    context = {'animateurs' : animateurs}

    return render(request, templateURL, context)

def animateur_details(request, animateur_id):
    # try:
    #     animateurs = Animateur.objects.filter(pk=animateur_id)
    #     context = {'animateur': animateurs[0]}
    # except DoesNotExist:
    #     raise Http404("Animateur does not exist")
    # return render(request, 'radio/animateur-details.html', context)
    animateur = get_object_or_404(Animateur, pk=animateur_id)
    return render(request, 'radio/animateur-details.html', {'animateur': animateur})

backend/radio/templates/radio/albums.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="radio-container">
  <div>
    {% for album in albums %}
      <div class="emission-wrapper wrapper">
        <div class="emission-panel panel">
          <div class="emission-panel-content">
            <div class="emission-header">
              <img src="{{ album.album_art }}" class="emission-image"/>
              <div class="emission-infos">
                <h1 class="emission-title"><a>{{ album.nom }} ({{album.annee}})</a></h1>
                <div class="emission-details">
                  <span class="tag">
                    <i class="fa fa-user"></i>
                    {{ album.artiste }}
                  </span>
                </div>
              </div>
            </div>
            <p class="emission-description">
              {{ album.description }}
            </p>
            {% if album.lien_phoenix %}
               <a class="button" href="{{album.lien_phoenix }}">
                 Télécharger sur Phoenix</a>
            {% endif %}
            {% if album.lien_deezer %}
               <a class="secondary-button" href="{{album.lien_deezer }}"><i class="fa fa-link">
               </i>Deezer</a>
            {% endif %}
            {% if album.lien_spotify  %}
               <a class="secondary-button" href="{{ album.lien_spotify }}"><i class="fa fa-spotify">
               </i>Spotify</a>
            {% endif %}
            {% if album.lien_youtube %}
               <a class="secondary-button" href="{{ album.lien_youtube }}"><i class="fa fa-youtube">
               </i>YouTube</a>
            {% endif %}
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

backend/radio/templates/radio/animateur-details.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<div class="radio-container">
  <div class="emission-wrapper wrapper">
    <div class="emission-panel panel">
      <div class="emission-panel-content">
        <div class="emission-header">
          <img src="{% static 'radio/img/animateur.jpg' %}" class="emission-image"/>
          <div class="emission-infos">
            <h1 class="emission-title">{{ animateur.prenom }} {{ animateur.nom }}</h1>
          <div class="emission-details">
            <span class="tag">
              <i class="fa fa-user"></i>
              {{ animateur.role }}
            </span>
            <span class="tag" onclick="toggleDisplay('.episodes');">
              <i class="fa fa-headphones"></i>{{ses_derniers_enregistrements|length }} émissions
            </span>
          </div></div>
        </div>
        <p class="emission-description">
          {{ animateur.presentation}}
        </p>
      </div>
      <div class="display-more" id="display-all" onclick="toggleDisplay('.episodes');"><i class="fa fa-ellipsis-h"></i></div>
    </div>
    <div class="episodes" hidden>
      {% for episode in ses_derniers_enregistrements %}
      <div class="episode-panel">
        <i class="fa fa-play" onclick="playPauseById(this, 'audio-{{episode.id}}');"></i>
        <a href="{% url 'radio:enregistrement_details' episode.id %}">
          {{ episode.emission.nom }} #{{episode.edition_id}} : {{episode.titre}}
        </a> -
        <span class="episode-date">le {{ episode.date_diffusion|date:'d/m' }}</span>
        <audio id="audio-{{episode.id}}" src="{% static 'radio/audio/demo.wav' %}"/>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

backend/radio/templates/radio/animateurs.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="radio-container">
  <div>
    {% for anim in animateurs %}
      <div class="emission-wrapper wrapper">
        <div class="emission-panel panel">
          <div class="emission-panel-content">
            <div class="emission-header">
              <img src="{% static 'radio/img/animateur.jpg' %}" class="emission-image"/>
              <div class="emission-infos">
                <h1 class="emission-title"><a href="{% url 'radio:animateur_details' anim.id %}">{{ anim.prenom }} {{ anim.nom }}</a></h1>
                <div class="emission-details">
                  <span class="tag">
                    <i class="fa fa-user"></i>
                    {% if anim.role %}
                      {{anim.role}}
                    {% endif %}
                  </span>
                </div>
              </div>
            </div>
            <p class="emission-description">
              {{ anim.presentation}}
            </p>
            {% if anim.allow_contact %}
             <a class="button" href="mailto:{{anim.email}}"><i class="fa fa-envelope">
             </i>Contacter</a>
             {% endif %}
            <a class="secondary-button"  href="{% url 'radio:animateur_details' anim.id%}">Réecouter ses émissions</a>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

backend/radio/templates/radio/emission-details.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<div class="radio-container">
  <div class="emission-wrapper wrapper">
    <div class="emission-panel panel">
      <div class="emission-panel-content">
        <div class="emission-header">
          <img src="{% static 'radio/img/cover-' %}{{ emission.id }}.jpg" class="emission-image"/>
          <div class="emission-infos"><h1 class="emission-title">{{ emission.nom }}</h1>
          <div class="emission-details">
            <span class="tag">
              <i class="fa fa-user"></i>{% for anim in emission.contributeurs.all %}
              <a class="contributeur" href="{% url 'radio:animateur_details' anim.id %}">{{anim.prenom}} {{anim.nom}}{% endfor %}</a>
            </span>
            <span class="tag" onclick="toggleDisplay('.episodes');">
              <i class="fa fa-headphones"></i> 9 épisodes
            </span>
          </div></div>
        </div>
        <p class="emission-description">
          {{ emission.description}}
        </p>
      </div>
      <div class="display-more" id="display-all" onclick="toggleDisplay('.episodes');"><i class="fa fa-ellipsis-h"></i></div>
    </div>
    <div class="episodes" hidden>
      {% for episode in derniers_enregistrements %}
      <div class="episode-panel">
        <i class="fa fa-play" onclick="playPauseById(this, 'audio-{{episode.id}}');"></i>
        <a href="{% url 'radio:enregistrement_details' episode.id %}">
          {{ emission.nom }} #{{episode.edition_id}} : {{episode.titre}}
        </a> -
        <span class="episode-date">le {{ episode.date_diffusion|date:'d/m' }}</span>
        <audio id="audio-{{episode.id}}" src="{% static 'radio/audio/demo.wav' %}"/>
      </div>
      {% endfor %}
    </div>
  </div>
</div>






<!--
<div class="radio-container">
  <h1>{{ emission.nom }}</h1>
  <p>{{ emission.date_derniere_diffusion }} </p>
  <h3>Dernières émissions :</h3>
  <ul> {% for ep in derniers_enregistrements %}
    <li class="episode-details">
      <h3><span class="emission-titre">
        <a href="{% url 'radio:enregistrement_details' ep.id %}">
          {{ ep.emission.nom }} #{{ ep.edition_id }} : {{ ep.titre}}
        </a></span>
      </h3>
      <h4><span class="titre">Emission du {{ ep.date_diffusion|date:'d/m'}}</span></h4>
      <p><span class="description">{{ ep.description }}</span></p>
      <button type="button" class="bouton-xray" onclick="togglePlayPause(this, 'enregistrement-{{emission.id}}-{{ep.edition_id}}');"><i class="fa fa-play"></i>Ecouter</button>
      <div id="enregistrement-{{emission.id}}-{{ep.edition_id}}" class="waveform-container">{{ep.emission_url}}</div>
    </li>
    {% endfor %}
  </ul>
</div>-->
{% endblock %}

backend/radio/templates/radio/emissions.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="radio-container">
  <div class="emissions-liste">
    {% for emission in emissions %}
      <div class="emission-wrapper wrapper">
        <div class="emission-panel panel">
          <div class="emission-panel-content">
            <div class="emission-header">
              <img src="{% static 'radio/img/cover-' %}{{ emission.id }}.jpg" class="emission-image"/>
              <div class="emission-infos"><h1 class="emission-title">{{ emission.nom }}</h1>
              <div class="emission-details">
                <span class="tag">
                  <i class="fa fa-user"></i>{% for anim in emission.contributeurs.all %}
                  <a class="contributeur" href="{% url 'radio:animateur_details' anim.id %}">{{anim.prenom}} {{anim.nom}}{% endfor %}</a>
                </span>
                <span class="tag" onclick="toggleDisplay('.episodes');">
                  <i class="fa fa-headphones"></i> 9 épisodes
                </span>
              </div></div>
            </div>
            <p class="emission-description">
              {{ emission.description}}
            </p>
            {% if emission.dernier_episode %}
            <a class="button" href="{% url 'radio:enregistrement_details' emission.dernier_episode.id %}">
              <i class="fa fa-play"></i>Réécouter la dernière émission
              ( {{ emission.dernier_episode.date_diffusion|date:'d/m'}} ) : {{ emission.dernier_episode.titre}}
            </a>
            {% endif %}
            <a class="secondary-button"  href="{% url 'radio:emission_details' emission.id%}">Voir tout</a>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

backend/radio/templates/radio/enregistrement-details.html
{% extends "index.html" %}

{% load static %}
{% block content %}


<div class="radio-container">
  <div class="episode-details">
    <h1>
      <a href="{% url 'radio:enregistrement_details' enregistrement.id %}">
        {{ enregistrement.emission.nom }} #{{ enregistrement.edition_id }} : {{ enregistrement.titre}}
      </a>
    </h1>
    <span class="tag">
      <a href="{% url 'radio:emission_details' enregistrement.emission.id %}">
        {{enregistrement.emission.nom}}
      </a>
    </span>
    <span class="tag">
      Emission du {{ enregistrement.date_diffusion|date:'d/m'}}
    </span>
    <p>
        {{ enregistrement.description }}
    </p>
    <button type="button" class="reverse-button" onclick="togglePlayPause(this, 'enregistrement-{{enregistrement.emission.id}}-{{enregistrement.edition_id}}');"><i class="fa fa-play"></i>Ecouter</button>
    <a class="reverse-button" href="{% static 'radio/audio/' %}{{enregistrement.emission_url}}" download="{{enregistrement.emission.nom}} #{{enregistrement.edition_id}}.mp3"><i class="fa fa-download"></i>Télécharger</a>
    </div>
</div>
<div id="enregistrement-{{enregistrement.emission.id}}-{{enregistrement.edition_id}}" class="waveform-container">{{enregistrement.emission_url}}</div>


{% endblock %}

backend/radio/templates/radio/enregistrements.html
{% extends "index.html" %}

{% load static %}
{% block content %}

<div class="radio-container">
  <div> {% for ep in enregistrements %}
      <div class="emission-wrapper wrapper">
        <div class="emission-panel panel">
          <div class="emission-panel-content">
            <div class="emission-header">
              <img src="{% static 'radio/img/cover-' %}{{ ep.emission.id }}.jpg" class="emission-image"/>
              <div class="emission-infos">
                <h2 class="emission-title">
                  <a href="{% url 'radio:emission_details' ep.emission.id %}">
                    {{ ep.emission.nom }} #{{ ep.edition_id }} :
                  </a>
                </h2>
                <h1 class="emission-title">
                  <a href="{% url 'radio:enregistrement_details' ep.id %}">
                    {{ ep.titre}}
                  </a>
                </h1>
              <div class="emission-details">
                <span class="tag">
                  <i class="fa fa-user"></i>{% for anim in ep.emission.contributeurs.all %}
                  <a class="contributeur" href="{% url 'radio:animateur_details' anim.id %}">{{anim.prenom}} {{anim.nom}}{% endfor %}</a>
                </span>
                <span class="tag" onclick="toggleDisplay('.episodes');">
                  <i class="fa fa-headphones"></i>Emission du {{ ep.date_diffusion|date:'d/m'}}
                </span>
              </div>
            </div>
            </div>
            <p class="emission-description">
              {{ ep.description}}
            </p>
            <button type="button" class="button" onclick="togglePlayPause(this, 'enregistrement-{{ep.emission.id}}-{{ep.edition_id}}');"><i class="fa fa-play"></i>Ecouter</button>
            <a class="secondary-button" href="{% static 'radio/audio/' %}{{ep.emission_url}}" download="{{ep.emission.nom}} #{{ep.edition_id}}.mp3"><i class="fa fa-download"></i>Télécharger</a>
            <div id="enregistrement-{{ep.emission.id}}-{{ep.edition_id}}" class="waveform-container-no-autoload">{{ep.emission_url}}</div>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

backend/radio/templates/radio/enregistrements0.html
{% extends "index.html" %}

{% block content %}

<h1>Derniers enregistrements</h1>
<ul>
  {% for enregistrement in enregistrements %}
    <li>
      <i>{{enregistrement.date_diffusion|date:"d/m"}} : </i>
      <a href="{% url 'radio:enregistrement_details' enregistrement.id %}">
      <strong>{{ enregistrement.emission.nom }} : </strong> {{enregistrement.titre}}</a></li>
  {% endfor %}
</ul>

{% endblock %}

backend/radio/templates/radio/participer.html
{% extends "index.html" %}

{% load static %}

{% block content %}

<p id="message-container"><span id="message">
  créer<br/>
  participer<br/>
  emprunter<br/>
</span></p>


<div class="radio-container">
  <h1>Viens participer aux émissions !</h1>
  <p>
    Viens parler de ta passion à l'antenne, on a toujours besoin de nouvelles idées et de nouveaux chroniqueurs.
    On peut te donner de l'aide pour préparer ton émission, l'enregistrer ou la monter. N'hésite pas !
    <br/>
    <br/>
    Et si tu veux simplement utiliser le local pour des activités perso ou binet,
    emprunter du matos ou écouter les CD de la diskhâle moderne,
    <br>
    <strong>aucun souci !</strong>
    Contacte-nous et on t'aidera :<br/>
    <a class="reverse-button" href="mailto:{{contact.email}}"><i class="fa fa-envelope">
    </i>Contacter</a>
  </p>
</div>



{% endblock %}

backend/radio/templates/radio/programmes.html
{% extends 'index.html' %}

{% block content %}
<div class="radio-container">
  <p>
    <strong>Retrouvez ici les temps forts de la grille musicale d'X-Ray.</strong>
    <br/>
    La plupart du temps, on diffuse une musique éclectique, en
    essayant de trouver un juste milieu entre nouveautés,
    pépites méconnues et grands classiques. Vous entendrez
    à l'antenne aussi bien de la folk, du rap, de la pop, de la
    chanson française, du jazz, de la musique électronique.
    <br/>
    La nuit, on passe essentiellement du jazz, mais parfois aussi
    des extraits audio tirés de romans, d'anciennes émissions, ou
    de podcasts extérieurs.<br/>
    <strong>
      Bonne écoute sur X-Ray !
    </strong>
  </p>
{% for item in data %}
  {% if item.programmes %}
    <h1 class="jour reverse-title">{{ item.jour }}</h1>
    {% for prog in item.programmes %}
      <div class="programme">
        <p>
          <em class="horaires">
            {{prog.heure_debut|date:"H:i"}} - {{prog.heure_fin|date:"H:i"}} :
          </em>
          {% if prog.titre %}
            <span class="reverse-tag playlist-player" data-playlist="{{prog.playlist_id}}" data-selector="#playlist-container-{{prog.id}}">
              {{prog.titre}}
            </span>
          {% endif %}
          <br/>
          {{ prog.description }}
        </p>
        <div id="playlist-container-{{prog.id}}"></div>
        </div>
    {% endfor %}
  {% endif %}
{% endfor %}
</div>
{% endblock %}